const books = [
  { title: "To Kill a Mockingbird" },
  { title: "1984" },
  { title: "Pride and Prejudice" },
  { title: "Harry Potter and the Philosopher's Stone" },
  { title: "The Lord of the Rings" },
  { title: "The Man in the Iron Mask" },
  { title: "The Catcher in the Rye" },
  { title: "A Game of Thrones" },
  { title: "The Deerslayer" },
  { title: "The Way of Kings" },
  { title: "Le Comte de Monte-Cristo" },
  { title: "Whose Body?" },
  { title: "The Great Gatsby" },
  { title: "The Odyssey" },
  { title: "Crime and Punishment" },
  { title: "The Brothers Karamazov" },
  { title: "Brave New World" },
  { title: "Wuthering Heights" },
  { title: "Jane Eyre" },
  { title: "The Hobbit" },
  { title: "Fahrenheit 451" },
  { title: "The Picture of Dorian Gray" },
  { title: "Dracula" },
  { title: "The Count of Monte Cristo" },
  { title: "Les Misérables" },
  { title: "Anna Karenina" },
  { title: "The Divine Comedy" },
  { title: "Don Quixote" },
  { title: "One Hundred Years of Solitude" },
  { title: "The Iliad" },
  { title: "Madame Bovary" },
  { title: "The Scarlet Letter" },
  { title: "Great Expectations" },
  { title: "The Grapes of Wrath" },
  { title: "A Tale of Two Cities" },
  { title: "Les Fleurs du mal" },
  { title: "Moby-Dick" },
  { title: "The Sun Also Rises" },
  { title: "Invisible Man" },
  { title: "Beloved" },
  { title: "The Sound and the Fury" },
  { title: "Mrs Dalloway" },
  { title: "The Old Man and the Sea" },
  { title: "The Handmaid's Tale" },
  { title: "Slaughterhouse-Five" },
  { title: "The Kite Runner" },
  { title: "Life of Pi" },
  { title: "The Alchemist" },
  { title: "Norwegian Wood" },
  { title: "The Road" },
  { title: "The Color Purple" },
  { title: "Midnight's Children" },
  { title: "The Stranger" },
  { title: "Siddhartha" },
  { title: "The Bell Jar" },
  { title: "On the Road" }
];

export default books;
